//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     //
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace SyncResultDataService
{
    using System.Runtime.Serialization;
    
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("dotnet-svcutil", "1.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="TestResultDTO", Namespace="http://schemas.datacontract.org/2004/07/TheS.eXam.FileManagementLibrary.DTOs")]
    public partial class TestResultDTO : object
    {
        
        private string APPLY_DATEField;
        
        private string CERT_NOField;
        
        private int CERT_YYField;
        
        private string CREATE_DATEField;
        
        private string CREATE_USER_CODEField;
        
        private string EXAM_DATEField;
        
        private int EXAM_FLAGField;
        
        private bool EXAM_RESULTField;
        
        private int EXAM_SCOREField;
        
        private bool IsPassField;
        
        private System.DateTime LAST_UPD_DATEField;
        
        private string OUT_COURSE_CODEField;
        
        private string PASS_EXAM_DATEField;
        
        private int PASS_NOField;
        
        private string PLT_CODEField;
        
        private string QDETAILField;
        
        private bool[] QxxField;
        
        private string REQ_DATEField;
        
        private string REQ_NOField;
        
        private string SEQ_NOField;
        
        private string UPD_USER_CODEField;
        
        private string UPD_USER_IDField;
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string APPLY_DATE
        {
            get
            {
                return this.APPLY_DATEField;
            }
            set
            {
                this.APPLY_DATEField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string CERT_NO
        {
            get
            {
                return this.CERT_NOField;
            }
            set
            {
                this.CERT_NOField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public int CERT_YY
        {
            get
            {
                return this.CERT_YYField;
            }
            set
            {
                this.CERT_YYField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string CREATE_DATE
        {
            get
            {
                return this.CREATE_DATEField;
            }
            set
            {
                this.CREATE_DATEField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string CREATE_USER_CODE
        {
            get
            {
                return this.CREATE_USER_CODEField;
            }
            set
            {
                this.CREATE_USER_CODEField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string EXAM_DATE
        {
            get
            {
                return this.EXAM_DATEField;
            }
            set
            {
                this.EXAM_DATEField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public int EXAM_FLAG
        {
            get
            {
                return this.EXAM_FLAGField;
            }
            set
            {
                this.EXAM_FLAGField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public bool EXAM_RESULT
        {
            get
            {
                return this.EXAM_RESULTField;
            }
            set
            {
                this.EXAM_RESULTField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public int EXAM_SCORE
        {
            get
            {
                return this.EXAM_SCOREField;
            }
            set
            {
                this.EXAM_SCOREField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public bool IsPass
        {
            get
            {
                return this.IsPassField;
            }
            set
            {
                this.IsPassField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public System.DateTime LAST_UPD_DATE
        {
            get
            {
                return this.LAST_UPD_DATEField;
            }
            set
            {
                this.LAST_UPD_DATEField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string OUT_COURSE_CODE
        {
            get
            {
                return this.OUT_COURSE_CODEField;
            }
            set
            {
                this.OUT_COURSE_CODEField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string PASS_EXAM_DATE
        {
            get
            {
                return this.PASS_EXAM_DATEField;
            }
            set
            {
                this.PASS_EXAM_DATEField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public int PASS_NO
        {
            get
            {
                return this.PASS_NOField;
            }
            set
            {
                this.PASS_NOField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string PLT_CODE
        {
            get
            {
                return this.PLT_CODEField;
            }
            set
            {
                this.PLT_CODEField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string QDETAIL
        {
            get
            {
                return this.QDETAILField;
            }
            set
            {
                this.QDETAILField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public bool[] Qxx
        {
            get
            {
                return this.QxxField;
            }
            set
            {
                this.QxxField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string REQ_DATE
        {
            get
            {
                return this.REQ_DATEField;
            }
            set
            {
                this.REQ_DATEField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string REQ_NO
        {
            get
            {
                return this.REQ_NOField;
            }
            set
            {
                this.REQ_NOField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string SEQ_NO
        {
            get
            {
                return this.SEQ_NOField;
            }
            set
            {
                this.SEQ_NOField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string UPD_USER_CODE
        {
            get
            {
                return this.UPD_USER_CODEField;
            }
            set
            {
                this.UPD_USER_CODEField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string UPD_USER_ID
        {
            get
            {
                return this.UPD_USER_IDField;
            }
            set
            {
                this.UPD_USER_IDField = value;
            }
        }
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("dotnet-svcutil", "1.0.0.0")]
    [System.ServiceModel.ServiceContractAttribute(ConfigurationName="SyncResultDataService.ISyncResultDataService")]
    public interface ISyncResultDataService
    {
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/ISyncResultDataService/SyncResultToFile", ReplyAction="http://tempuri.org/ISyncResultDataService/SyncResultToFileResponse")]
        System.Threading.Tasks.Task SyncResultToFileAsync(SyncResultDataService.TestResultDTO[] result);
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("dotnet-svcutil", "1.0.0.0")]
    public interface ISyncResultDataServiceChannel : SyncResultDataService.ISyncResultDataService, System.ServiceModel.IClientChannel
    {
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("dotnet-svcutil", "1.0.0.0")]
    public partial class SyncResultDataServiceClient : System.ServiceModel.ClientBase<SyncResultDataService.ISyncResultDataService>, SyncResultDataService.ISyncResultDataService
    {
        
    /// <summary>
    /// Implement this partial method to configure the service endpoint.
    /// </summary>
    /// <param name="serviceEndpoint">The endpoint to configure</param>
    /// <param name="clientCredentials">The client credentials</param>
    static partial void ConfigureEndpoint(System.ServiceModel.Description.ServiceEndpoint serviceEndpoint, System.ServiceModel.Description.ClientCredentials clientCredentials);
        
        public SyncResultDataServiceClient() : 
                base(SyncResultDataServiceClient.GetDefaultBinding(), SyncResultDataServiceClient.GetDefaultEndpointAddress())
        {
            this.Endpoint.Name = EndpointConfiguration.BasicHttpBinding_ISyncResultDataService.ToString();
            ConfigureEndpoint(this.Endpoint, this.ClientCredentials);
        }
        
        public SyncResultDataServiceClient(EndpointConfiguration endpointConfiguration) : 
                base(SyncResultDataServiceClient.GetBindingForEndpoint(endpointConfiguration), SyncResultDataServiceClient.GetEndpointAddress(endpointConfiguration))
        {
            this.Endpoint.Name = endpointConfiguration.ToString();
            ConfigureEndpoint(this.Endpoint, this.ClientCredentials);
        }
        
        public SyncResultDataServiceClient(EndpointConfiguration endpointConfiguration, string remoteAddress) : 
                base(SyncResultDataServiceClient.GetBindingForEndpoint(endpointConfiguration), new System.ServiceModel.EndpointAddress(remoteAddress))
        {
            this.Endpoint.Name = endpointConfiguration.ToString();
            ConfigureEndpoint(this.Endpoint, this.ClientCredentials);
        }
        
        public SyncResultDataServiceClient(EndpointConfiguration endpointConfiguration, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(SyncResultDataServiceClient.GetBindingForEndpoint(endpointConfiguration), remoteAddress)
        {
            this.Endpoint.Name = endpointConfiguration.ToString();
            ConfigureEndpoint(this.Endpoint, this.ClientCredentials);
        }
        
        public SyncResultDataServiceClient(System.ServiceModel.Channels.Binding binding, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(binding, remoteAddress)
        {
        }
        
        public System.Threading.Tasks.Task SyncResultToFileAsync(SyncResultDataService.TestResultDTO[] result)
        {
            return base.Channel.SyncResultToFileAsync(result);
        }
        
        public virtual System.Threading.Tasks.Task OpenAsync()
        {
            return System.Threading.Tasks.Task.Factory.FromAsync(((System.ServiceModel.ICommunicationObject)(this)).BeginOpen(null, null), new System.Action<System.IAsyncResult>(((System.ServiceModel.ICommunicationObject)(this)).EndOpen));
        }
        
        public virtual System.Threading.Tasks.Task CloseAsync()
        {
            return System.Threading.Tasks.Task.Factory.FromAsync(((System.ServiceModel.ICommunicationObject)(this)).BeginClose(null, null), new System.Action<System.IAsyncResult>(((System.ServiceModel.ICommunicationObject)(this)).EndClose));
        }
        
        private static System.ServiceModel.Channels.Binding GetBindingForEndpoint(EndpointConfiguration endpointConfiguration)
        {
            if ((endpointConfiguration == EndpointConfiguration.BasicHttpBinding_ISyncResultDataService))
            {
                System.ServiceModel.BasicHttpBinding result = new System.ServiceModel.BasicHttpBinding();
                result.MaxBufferSize = int.MaxValue;
                result.ReaderQuotas = System.Xml.XmlDictionaryReaderQuotas.Max;
                result.MaxReceivedMessageSize = int.MaxValue;
                result.AllowCookies = true;
                return result;
            }
            throw new System.InvalidOperationException(string.Format("Could not find endpoint with name \'{0}\'.", endpointConfiguration));
        }
        
        private static System.ServiceModel.EndpointAddress GetEndpointAddress(EndpointConfiguration endpointConfiguration)
        {
            if ((endpointConfiguration == EndpointConfiguration.BasicHttpBinding_ISyncResultDataService))
            {
                return new System.ServiceModel.EndpointAddress("http://61.91.64.134/DataSyncResult/Services/SyncResultDataService.svc");
            }
            throw new System.InvalidOperationException(string.Format("Could not find endpoint with name \'{0}\'.", endpointConfiguration));
        }
        
        private static System.ServiceModel.Channels.Binding GetDefaultBinding()
        {
            return SyncResultDataServiceClient.GetBindingForEndpoint(EndpointConfiguration.BasicHttpBinding_ISyncResultDataService);
        }
        
        private static System.ServiceModel.EndpointAddress GetDefaultEndpointAddress()
        {
            return SyncResultDataServiceClient.GetEndpointAddress(EndpointConfiguration.BasicHttpBinding_ISyncResultDataService);
        }
        
        public enum EndpointConfiguration
        {
            
            BasicHttpBinding_ISyncResultDataService,
        }
    }
}
